Deep Learning
=============

Assignment 2
------------

Previously in `1_notmnist.ipynb`, we created a pickle with formatted datasets for training, development and testing on the [notMNIST dataset](http://yaroslavvb.blogspot.com/2011/09/notmnist-dataset.html).

The goal of this assignment is to progressively train deeper and more accurate models using TensorFlow.

In [1]:
# These are all the modules we'll be using later. Make sure you can import them
# before proceeding further.
from __future__ import print_function
import numpy as np
import tensorflow as tf
from six.moves import cPickle as pickle
from six.moves import range

First reload the data we generated in `1_notmnist.ipynb`.

In [6]:
pickle_file = 'notMNIST.pickle'

with open(pickle_file, 'rb') as f:
  save = pickle.load(f)
  train_dataset = save['train_dataset']
  train_labels = save['train_labels']
  valid_dataset = save['valid_dataset']
  valid_labels = save['valid_labels']
  test_dataset = save['test_dataset']
  test_labels = save['test_labels']
  del save  # hint to help gc free up memory
  print('Training set', train_dataset.shape, train_labels.shape)
  print('Validation set', valid_dataset.shape, valid_labels.shape)
  print('Test set', test_dataset.shape, test_labels.shape)

Training set (200000, 28, 28) (200000,)
Validation set (10000, 28, 28) (10000,)
Test set (10000, 28, 28) (10000,)


Reformat into a shape that's more adapted to the models we're going to train:
- data as a flat matrix,
- labels as float 1-hot encodings.

In [7]:
image_size = 28
num_labels = 10

def reformat(dataset, labels):
  dataset = dataset.reshape((-1, image_size * image_size)).astype(np.float32)
  # Map 0 to [1.0, 0.0, 0.0 ...], 1 to [0.0, 1.0, 0.0 ...]
  labels = (np.arange(num_labels) == labels[:,None]).astype(np.float32)
  return dataset, labels
train_dataset, train_labels = reformat(train_dataset, train_labels)
valid_dataset, valid_labels = reformat(valid_dataset, valid_labels)
test_dataset, test_labels = reformat(test_dataset, test_labels)
print('Training set', train_dataset.shape, train_labels.shape)
print('Validation set', valid_dataset.shape, valid_labels.shape)
print('Test set', test_dataset.shape, test_labels.shape)

[7 4 5 ..., 7 9 3]
-------
[[7]
 [4]
 [5]
 ..., 
 [7]
 [9]
 [3]]
[4 5 8 ..., 7 1 0]
-------
[[4]
 [5]
 [8]
 ..., 
 [7]
 [1]
 [0]]
[2 6 0 ..., 2 7 6]
-------
[[2]
 [6]
 [0]
 ..., 
 [2]
 [7]
 [6]]
Training set (200000, 784) (200000, 10)
Validation set (10000, 784) (10000, 10)
Test set (10000, 784) (10000, 10)


We're first going to train a multinomial logistic regression using simple gradient descent.

TensorFlow works like this:
* First you describe the computation that you want to see performed: what the inputs, the variables, and the operations look like. These get created as nodes over a computation graph. This description is all contained within the block below:

      with graph.as_default():
          ...

* Then you can run the operations on this graph as many times as you want by calling `session.run()`, providing it outputs to fetch from the graph that get returned. This runtime operation is all contained in the block below:

      with tf.Session(graph=graph) as session:
          ...

Let's load all the data into TensorFlow and build the computation graph corresponding to our training:

In [9]:
# With gradient descent training, even this much data is prohibitive.
# Subset the training data for faster turnaround.
train_subset = 10000

graph = tf.Graph()
with graph.as_default():

  # Input data.
  # Load the training, validation and test data into constants that are
  # attached to the graph.
  tf_train_dataset = tf.constant(train_dataset[:train_subset, :])
  tf_train_labels = tf.constant(train_labels[:train_subset])
  tf_valid_dataset = tf.constant(valid_dataset)
  tf_test_dataset = tf.constant(test_dataset)
  
  # Variables.
  # These are the parameters that we are going to be training. The weight
  # matrix will be initialized using random values following a (truncated)
  # normal distribution. The biases get initialized to zero.
  weights = tf.Variable(
    tf.truncated_normal([image_size * image_size, num_labels]))
  biases = tf.Variable(tf.zeros([num_labels]))
  
  # Training computation.
  # We multiply the inputs with the weight matrix, and add biases. We compute
  # the softmax and cross-entropy (it's one operation in TensorFlow, because
  # it's very common, and it can be optimized). We take the average of this
  # cross-entropy across all training examples: that's our loss.
  logits = tf.matmul(tf_train_dataset, weights) + biases
  loss = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits(labels=tf_train_labels, logits=logits))
  
  # Optimizer.
  # We are going to find the minimum of this loss using gradient descent.
  optimizer = tf.train.GradientDescentOptimizer(0.5).minimize(loss)
  
  # Predictions for the training, validation, and test data.
  # These are not part of training, but merely here so that we can report
  # accuracy figures as we train.
  train_prediction = tf.nn.softmax(logits)
  valid_prediction = tf.nn.softmax(
    tf.matmul(tf_valid_dataset, weights) + biases)
  test_prediction = tf.nn.softmax(tf.matmul(tf_test_dataset, weights) + biases)

Let's run this computation and iterate:

In [10]:
num_steps = 801

def accuracy(predictions, labels):
  return (100.0 * np.sum(np.argmax(predictions, 1) == np.argmax(labels, 1))
          / predictions.shape[0])

with tf.Session(graph=graph) as session:
  # This is a one-time operation which ensures the parameters get initialized as
  # we described in the graph: random weights for the matrix, zeros for the
  # biases. 
  tf.global_variables_initializer().run()
  print('Initialized')
  for step in range(num_steps):
    # Run the computations. We tell .run() that we want to run the optimizer,
    # and get the loss value and the training predictions returned as numpy
    # arrays.
    _, l, predictions = session.run([optimizer, loss, train_prediction])
    if (step % 100 == 0):
      print('Loss at step %d: %f' % (step, l))
      print('Training accuracy: %.1f%%' % accuracy(
        predictions, train_labels[:train_subset, :]))
      # Calling .eval() on valid_prediction is basically like calling run(), but
      # just to get that one numpy array. Note that it recomputes all its graph
      # dependencies.
      print('Validation accuracy: %.1f%%' % accuracy(
        valid_prediction.eval(), valid_labels))
  print('Test accuracy: %.1f%%' % accuracy(test_prediction.eval(), test_labels))

Initialized
Loss at step 0: 18.405306
Training accuracy: 6.7%
Validation accuracy: 9.7%
Loss at step 100: 2.167906
Training accuracy: 72.6%
Validation accuracy: 71.1%
Loss at step 200: 1.753832
Training accuracy: 75.6%
Validation accuracy: 73.5%
Loss at step 300: 1.530905
Training accuracy: 77.0%
Validation accuracy: 74.4%
Loss at step 400: 1.379171
Training accuracy: 77.8%
Validation accuracy: 74.8%
Loss at step 500: 1.265787
Training accuracy: 78.6%
Validation accuracy: 75.1%
Loss at step 600: 1.176112
Training accuracy: 79.0%
Validation accuracy: 75.3%
Loss at step 700: 1.102606
Training accuracy: 79.4%
Validation accuracy: 75.5%
Loss at step 800: 1.040895
Training accuracy: 79.9%
Validation accuracy: 75.9%
Test accuracy: 83.0%


Let's now switch to stochastic gradient descent training instead, which is much faster.

The graph will be similar, except that instead of holding all the training data into a constant node, we create a `Placeholder` node which will be fed actual data at every call of `session.run()`.

In [11]:
batch_size = 128

graph = tf.Graph()
with graph.as_default():

  # Input data. For the training data, we use a placeholder that will be fed
  # at run time with a training minibatch.
  tf_train_dataset = tf.placeholder(tf.float32,
                                    shape=(batch_size, image_size * image_size))
  tf_train_labels = tf.placeholder(tf.float32, shape=(batch_size, num_labels))
  tf_valid_dataset = tf.constant(valid_dataset)
  tf_test_dataset = tf.constant(test_dataset)
  
  # Variables.
  weights = tf.Variable(
    tf.truncated_normal([image_size * image_size, num_labels]))
  biases = tf.Variable(tf.zeros([num_labels]))
  
  # Training computation.
  logits = tf.matmul(tf_train_dataset, weights) + biases
  loss = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits(labels=tf_train_labels, logits=logits))
  
  # Optimizer.
  optimizer = tf.train.GradientDescentOptimizer(0.5).minimize(loss)
  
  # Predictions for the training, validation, and test data.
  train_prediction = tf.nn.softmax(logits)
  valid_prediction = tf.nn.softmax(
    tf.matmul(tf_valid_dataset, weights) + biases)
  test_prediction = tf.nn.softmax(tf.matmul(tf_test_dataset, weights) + biases)

Let's run it:

In [12]:
num_steps = 3001

with tf.Session(graph=graph) as session:
  tf.global_variables_initializer().run()
  print("Initialized")
  for step in range(num_steps):
    # Pick an offset within the training data, which has been randomized.
    # Note: we could use better randomization across epochs.
    offset = (step * batch_size) % (train_labels.shape[0] - batch_size)
    # Generate a minibatch.
    batch_data = train_dataset[offset:(offset + batch_size), :]
    batch_labels = train_labels[offset:(offset + batch_size), :]
    # Prepare a dictionary telling the session where to feed the minibatch.
    # The key of the dictionary is the placeholder node of the graph to be fed,
    # and the value is the numpy array to feed to it.
    feed_dict = {tf_train_dataset : batch_data, tf_train_labels : batch_labels}
    _, l, predictions = session.run(
      [optimizer, loss, train_prediction], feed_dict=feed_dict)
    if (step % 500 == 0):
      print("Minibatch loss at step %d: %f" % (step, l))
      print("Minibatch accuracy: %.1f%%" % accuracy(predictions, batch_labels))
      print("Validation accuracy: %.1f%%" % accuracy(
        valid_prediction.eval(), valid_labels))
  print("Test accuracy: %.1f%%" % accuracy(test_prediction.eval(), test_labels))

Initialized
Minibatch loss at step 0: 15.604495
Minibatch accuracy: 13.3%
Validation accuracy: 10.1%
Minibatch loss at step 500: 1.631445
Minibatch accuracy: 76.6%
Validation accuracy: 75.1%
Minibatch loss at step 1000: 1.078249
Minibatch accuracy: 82.0%
Validation accuracy: 76.2%
Minibatch loss at step 1500: 1.345274
Minibatch accuracy: 76.6%
Validation accuracy: 76.9%
Minibatch loss at step 2000: 1.006552
Minibatch accuracy: 78.1%
Validation accuracy: 77.9%
Minibatch loss at step 2500: 0.694602
Minibatch accuracy: 79.7%
Validation accuracy: 77.7%
Minibatch loss at step 3000: 0.862156
Minibatch accuracy: 79.7%
Validation accuracy: 78.5%
Test accuracy: 86.4%


---
Problem
-------

Turn the logistic regression example with SGD into a 1-hidden layer neural network with rectified linear units [nn.relu()](https://www.tensorflow.org/versions/r0.7/api_docs/python/nn.html#relu) and 1024 hidden nodes. This model should improve your validation / test accuracy.

---

In [27]:
graph = tf.Graph()
with graph.as_default():
    tf_train_dataset = tf.placeholder(tf.float32,shape=(None,image_size*image_size))
    tf_train_labels = tf.placeholder(tf.float32,shape=(None,num_labels))
    
    weights = {
        'hidden':tf.Variable(tf.truncated_normal([image_size*image_size,64])),
        'output':tf.Variable(tf.truncated_normal([64,10]))
    }
    biases = {
        'hidden':tf.Variable(tf.zeros(64)),
        'output':tf.Variable(tf.zeros(10))
    }
    
    hidden_layer = tf.matmul(tf_train_dataset,weights['hidden'])+biases['hidden']
    hidden_layer = tf.nn.relu(hidden_layer)
    output = tf.matmul(hidden_layer,weights['output'])+biases['output']
    
    loss = tf.reduce_mean(
        tf.nn.softmax_cross_entropy_with_logits(labels=tf_train_labels,logits=output))
    
    optimizer = tf.train.GradientDescentOptimizer(0.5).minimize(loss)
    
    pred = tf.nn.softmax(output)
    
num_steps = 10001
batch_size = 128

with tf.Session(graph=graph) as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(num_steps):
        offset = (step*batch_size)%(train_labels.shape[0] - batch_size)
        
        batch_data = train_dataset[offset:(offset+batch_size),:]
        batch_labels = train_labels[offset:(offset+batch_size),:]
        
        feed_dict = {tf_train_dataset:batch_data,tf_train_labels:batch_labels}
        _,l,predictions = sess.run([optimizer,loss,pred],feed_dict=feed_dict)
        
        if(step%500==0):
            print("Minibatch loss at step %d: %f" % (step, l))
            print("Minibatch accuracy: %.1f%%" % accuracy(predictions, batch_labels))
            print("Validation accuracy: %.1f%%" % accuracy(
                pred.eval(feed_dict={tf_train_dataset:valid_dataset}), valid_labels))
    print("Test accuracy: %.1f%%" % accuracy(
        pred.eval(feed_dict={tf_train_dataset:test_dataset}), test_labels))

Minibatch loss at step 0: 98.652924
Minibatch accuracy: 7.0%
Validation accuracy: 26.2%
Minibatch loss at step 500: 2.756810
Minibatch accuracy: 72.7%
Validation accuracy: 62.8%
Minibatch loss at step 1000: 0.782948
Minibatch accuracy: 78.1%
Validation accuracy: 76.6%
Minibatch loss at step 1500: 1.302223
Minibatch accuracy: 69.5%
Validation accuracy: 75.1%
Minibatch loss at step 2000: 0.906965
Minibatch accuracy: 83.6%
Validation accuracy: 78.1%
Minibatch loss at step 2500: 0.534954
Minibatch accuracy: 82.8%
Validation accuracy: 79.8%
Minibatch loss at step 3000: 0.626954
Minibatch accuracy: 80.5%
Validation accuracy: 80.2%
Minibatch loss at step 3500: 0.911110
Minibatch accuracy: 76.6%
Validation accuracy: 80.5%
Minibatch loss at step 4000: 0.846346
Minibatch accuracy: 78.9%
Validation accuracy: 80.5%
Minibatch loss at step 4500: 0.755140
Minibatch accuracy: 83.6%
Validation accuracy: 79.2%
Minibatch loss at step 5000: 0.461953
Minibatch accuracy: 85.2%
Validation accuracy: 81.3%
Min